### ISSUE TITLE
Sent message not in sent and inbox

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/InterCom#107]
I can send a message.
It does not appear in the inbox and the sent box.

**Comment by Kaik** [comment]
Ok, this should work inbox and sent at least... other boxes and counts... I need to do more tests actually whole https://github.com/zikula-modules/InterCom/blob/v3/Entity/Repository/MessagesRepository.php need to be reviewed by someone with good query builder doctrine knowledge.

**Comment by Kaik** [comment]
Hmm, it does not work properly, you can still play with it because it shows a message on the list etc... but as I have expected the query needs to be more sophisticated... I will get there eventually, but it will take me some time since I need to learn a lot about query builder and do a lot of testing...

**Comment by Portugao** [comment]
No problem; I decided to build a small solution for that in my module. The private message feature has to be as simple as possible for me....
Thx and fun during your process of learning.

**Comment by Kaik** [comment]
Ok, I figured it out and now things work as expected. 
@Portugao yes InterCom is a bit complicated but for sure you will be able to turn off most of the features.
I have read all previous feature requests and tried to come up with proper db schema to incorporate most of them... of course, not all of them will be working in first releases (like group sender/recipient), but db schema is able to handle it well... at least most of it.
