### ISSUE TITLE
Attaching files to messages

### ISSUE THREAD

**Issue by hvorragend** [zikula-modules/InterCom#21]
Description

Could it be possible to add the ability to attach files (images) to messages in InterCom???

Users are asking for this feature..
Attachments
Change History
comment:1 follow-up: ↓ 2 Changed 2 years ago by Landseer

Should be possible with MediaAttach? and some template changes. We will see...
comment:2 in reply to: ↑ 1 Changed 2 years ago by BlackChart

Replying to Landseer:

```
Should be possible with MediaAttach? and some template changes. We will see...
```

Is it possible to get a copy of MediaAttach? somewhere?

**Comment by Kaik** [comment]
Another module should provide this functionality via hooks.
