### ISSUE TITLE
For each of the recommended module dependencies, a "reason" should be populated in the array

### ISSUE THREAD

**Issue by shefik** [zikula-modules/InterCom#77]
In the InterComModuleVersion.php file, for each of the recommended module dependencies, a "reason" should be populated in the array, so that is can be display in the module's installation page. See attached screenshot.

![reason](https://cloud.githubusercontent.com/assets/274862/6744678/dcf8bab0-ce82-11e4-98cd-97632289c916.png)

**Comment by Kaik** [comment]
This is fixed.
